apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer
  name: reflectje-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer
    spec:
      containers:
        - image: ibudasov/reflectje:0.1
          name: reflectje-container
          ports:
            - containerPort: 8080