apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    purpose: cluster-with-load-balancer
    version: "0.1"
    stage: dev
  name: reflectje-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: cluster-with-load-balancer
  template:
    metadata:
      labels:
        purpose: cluster-with-load-balancer
    spec:
      containers:
        - image: ibudasov/reflectje:0.1
          name: reflectje-container
          ports:
            - containerPort: 8080