---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Install Python
      command: apk add --no-cache --update python3
      become: yes
      become_method: sudo
    - name: Install some python libs, which are needed for Ansible
      command: pip3 install --upgrade pip setuptools wheel docker-py
      become: yes
      become_method: sudo
    - name: Logging into DockerHub TODO HIDE CREDENTIALS!
      docker_login:
        username: ibudasov
        email: igor.budasov@gmail.com
        password: dreams
      become: yes
      become_method: sudo
    - name: Add a generic tag (ibudasov/reflectje:0.1)
      command: docker tag reflectje ibudasov/reflectje:0.1
      become: yes
      become_method: sudo
    - name: Push to ibudasov/reflectje
      command: docker push ibudasov/reflectje:0.1
      become: yes
      become_method: sudo

