---
- hosts: localhost
  remote_user: root
  tasks:
    - name: install Docker
      command: apk add docker
      become: yes
      become_method: sudo
    - name: run Docker daemon
      command: service docker start
      become: yes
      become_method: sudo