---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Stopping reflectje container. Check it - echo $(wget localhost -q -O -)
      docker_container:
        name: running-reflectje
        state: stopped
      become: yes
      become_method: sudo

