FROM openjdk:7-alpine

# Set the working directory.
# WORKDIR /usr/src/reflectje

RUN apk add git

RUN git clone https://github.com/ibudasov/reflectje.git

RUN apk add --no-cache openjdk8

RUN apk add maven
