---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Install Docker
      command: apk add docker
      become: yes
      become_method: sudo
    - name: Start Docker daemon, if not started
      service:
        name: docker
        state: started
      become: yes
      become_method: sudo
    - name: Make me Igor!
      command: git config user.name "Igor Budasov"
    - name: Make me Igor with email!
      command: git config user.email "igor.budasov@gmail.com"
