---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Download Kubernetes v1.18.0
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
        dest: .
      become: yes
      become_method: sudo
    - name: Move the binary in to your PATH and make it executable
      copy:
        src: ./kubectl
        dest: /usr/local/bin/kubectl
        mode: a+x
      become: yes
      become_method: sudo
    - name: Let's check it!
      command: kubectl version --client
