---
- hosts: localhost
  remote_user: root
  tasks:
    - name: (RE)Run reflectje container in detached mode with exposing localhost:80. Check it - echo $(wget localhost -q -O -)
      docker_container:
        name: running-reflectje
        image: reflectje
        ports:
          - "80:8080"
        detach: yes
        restart: yes

