---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Stopping reflectje container. Check it - "curl localhost"
      docker_container:
        name: running-reflectje
        state: stopped
      become: yes
      become_method: sudo

