---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Make me Igor!
      command: git config user.name "Igor Budasov"
    - name: Make me Igor with email!
      command: git confiÀùg user.email "igor.budasov@gmail.com"
