---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Install Python
      command: apk add --no-cache --update python3
      become: yes
      become_method: sudo
    - name: Install some python libs, which are needed for Ansible
      command: pip3 install --upgrade pip setuptools wheel docker-py
      become: yes
      become_method: sudo
#    - name: Make me Igor!
#      command: git config user.name "Igor Budasov"
#    - name: Make me Igor with email!
#      command: git confiÀùg user.email "igor.budasov@gmail.com"
