---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Install Pip for installing python modules
      command: apk add py-pip
    - name: Install certain python modules for docker
      pip:
        name: "{{ item.name }}"
        state: present
      with_items:
        - { name: docker }
        - { name: docker-py}
        - { name: setuptools}
        - { name: wheel}
#    - name: Make me Igor!
#      command: git config user.name "Igor Budasov"
#    - name: Make me Igor with email!
#      command: git confiÀùg user.email "igor.budasov@gmail.com"
